"""生态指标映射与机理解释（AVONET 数据集）。

职责：
  1. 加载 AVONET 性状表（xlsx）。
  2. 通过"俗名 -> 学名"映射，把 CUB-200-2011 的 200 个鸟类类别对到 AVONET 物种。
  3. 输出特征-性状关联的可解释结论。

学名映射来源：cub-hierarchy（Wikispecies 层级，https://github.com/WanQiyang/cub-hierarchy）。
其中 4 个类别在原数据中只到属级，此处按常见资料定到种并加 note 标注。
"""
import pandas as pd

from . import config

# 默认 AVONET 文件路径
AVONET_PATH = config.ROOT / "data" / "AVONET Supplementary dataset 1.xlsx"

# CUB 类别号(1..200) -> (俗名, 学名, 备注)
# 备注标记 genus= 原数据仅属级，此处为定种结果，建议人工复核。
CUB_TO_SCIENTIFIC = {
    1: ("Black_footed_Albatross", "Phoebastria nigripes", ""),
    2: ("Laysan_Albatross", "Phoebastria immutabilis", ""),
    3: ("Sooty_Albatross", "Phoebetria fusca", ""),
    4: ("Groove_billed_Ani", "Crotophaga sulcirostris", ""),
    5: ("Crested_Auklet", "Aethia cristatella", ""),
    6: ("Least_Auklet", "Aethia pusilla", ""),
    7: ("Parakeet_Auklet", "Aethia psittacula", ""),
    8: ("Rhinoceros_Auklet", "Cerorhinca monocerata", ""),
    9: ("Brewer_Blackbird", "Euphagus cyanocephalus", ""),
    10: ("Red_winged_Blackbird", "Agelaius phoeniceus", ""),
    11: ("Rusty_Blackbird", "Euphagus carolinus", ""),
    12: ("Yellow_headed_Blackbird", "Xanthocephalus xanthocephalus", ""),
    13: ("Bobolink", "Dolichonyx oryzivorus", ""),
    14: ("Indigo_Bunting", "Passerina cyanea", ""),
    15: ("Lazuli_Bunting", "Passerina amoena", ""),
    16: ("Painted_Bunting", "Passerina ciris", ""),
    17: ("Cardinal", "Cardinalis cardinalis", ""),
    18: ("Spotted_Catbird", "Ailuroedus melanotis", ""),
    19: ("Gray_Catbird", "Dumetella carolinensis", ""),
    20: ("Yellow_breasted_Chat", "Icteria virens", ""),
    21: ("Eastern_Towhee", "Pipilo erythrophthalmus", ""),
    22: ("Chuck_will_Widow", "Caprimulgus carolinensis", ""),
    23: ("Brandt_Cormorant", "Phalacrocorax penicillatus", ""),
    24: ("Red_faced_Cormorant", "Phalacrocorax urile", ""),
    25: ("Pelagic_Cormorant", "Phalacrocorax pelagicus", ""),
    26: ("Bronzed_Cowbird", "Molothrus aeneus", ""),
    27: ("Shiny_Cowbird", "Molothrus bonariensis", ""),
    28: ("Brown_Creeper", "Certhia americana", ""),
    29: ("American_Crow", "Corvus brachyrhynchos", ""),
    30: ("Fish_Crow", "Corvus ossifragus", ""),
    31: ("Black_billed_Cuckoo", "Coccyzus erythropthalmus", ""),
    32: ("Mangrove_Cuckoo", "Coccyzus minor", ""),
    33: ("Yellow_billed_Cuckoo", "Coccyzus americanus", ""),
    34: ("Gray_crowned_Rosy_Finch", "Leucosticte tephrocotis", ""),
    35: ("Purple_Finch", "Haemorhous purpureus", ""),
    36: ("Northern_Flicker", "Colaptes auratus", ""),
    37: ("Acadian_Flycatcher", "Empidonax virescens", ""),
    38: ("Great_Crested_Flycatcher", "Myiarchus crinitus", ""),
    39: ("Least_Flycatcher", "Empidonax minimus", ""),
    40: ("Olive_sided_Flycatcher", "Contopus cooperi", ""),
    41: ("Scissor_tailed_Flycatcher", "Tyrannus forficatus", ""),
    42: ("Vermilion_Flycatcher", "Pyrocephalus rubinus", "异名:obscurus"),
    43: ("Yellow_bellied_Flycatcher", "Empidonax flaviventris", ""),
    44: ("Frigatebird", "Fregata magnificens", "genus=定种为华丽军舰鸟"),
    45: ("Northern_Fulmar", "Fulmarus glacialis", ""),
    46: ("Gadwall", "Mareca strepera", ""),
    47: ("American_Goldfinch", "Spinus tristis", ""),
    48: ("European_Goldfinch", "Carduelis carduelis", ""),
    49: ("Boat_tailed_Grackle", "Quiscalus major", ""),
    50: ("Eared_Grebe", "Podiceps nigricollis", ""),
    51: ("Horned_Grebe", "Podiceps auritus", ""),
    52: ("Pied_billed_Grebe", "Podilymbus podiceps", ""),
    53: ("Western_Grebe", "Aechmophorus occidentalis", ""),
    54: ("Blue_Grosbeak", "Passerina caerulea", ""),
    55: ("Evening_Grosbeak", "Hesperiphona vespertina", ""),
    56: ("Pine_Grosbeak", "Pinicola enucleator", ""),
    57: ("Rose_breasted_Grosbeak", "Pheucticus ludovicianus", ""),
    58: ("Pigeon_Guillemot", "Cepphus columba", ""),
    59: ("California_Gull", "Larus californicus", ""),
    60: ("Glaucous_winged_Gull", "Larus glaucescens", ""),
    61: ("Heermann_Gull", "Larus heermanni", ""),
    62: ("Herring_Gull", "Larus argentatus", ""),
    63: ("Ivory_Gull", "Pagophila eburnea", ""),
    64: ("Ring_billed_Gull", "Larus delawarensis", ""),
    65: ("Slaty_backed_Gull", "Larus schistisagus", ""),
    66: ("Western_Gull", "Larus occidentalis", ""),
    67: ("Anna_Hummingbird", "Calypte anna", ""),
    68: ("Ruby_throated_Hummingbird", "Archilochus colubris", ""),
    69: ("Rufous_Hummingbird", "Selasphorus rufus", ""),
    70: ("Green_Violetear", "Colibri thalassinus", ""),
    71: ("Long_tailed_Jaeger", "Stercorarius longicaudus", ""),
    72: ("Pomarine_Jaeger", "Stercorarius pomarinus", ""),
    73: ("Blue_Jay", "Cyanocitta cristata", ""),
    74: ("Florida_Jay", "Aphelocoma coerulescens", ""),
    75: ("Green_Jay", "Cyanocorax luxuosus", ""),
    76: ("Dark_eyed_Junco", "Junco hyemalis", ""),
    77: ("Tropical_Kingbird", "Tyrannus melancholicus", ""),
    78: ("Gray_Kingbird", "Tyrannus dominicensis", ""),
    79: ("Belted_Kingfisher", "Megaceryle alcyon", ""),
    80: ("Green_Kingfisher", "Chloroceryle americana", ""),
    81: ("Pied_Kingfisher", "Ceryle rudis", ""),
    82: ("Ringed_Kingfisher", "Megaceryle torquata", ""),
    83: ("White_breasted_Kingfisher", "Halcyon smyrnensis", ""),
    84: ("Red_legged_Kittiwake", "Rissa brevirostris", ""),
    85: ("Horned_Lark", "Eremophila alpestris", ""),
    86: ("Pacific_Loon", "Gavia pacifica", ""),
    87: ("Mallard", "Anas platyrhynchos", ""),
    88: ("Western_Meadowlark", "Sturnella neglecta", ""),
    89: ("Hooded_Merganser", "Lophodytes cucullatus", ""),
    90: ("Red_breasted_Merganser", "Mergus serrator", ""),
    91: ("Mockingbird", "Mimus polyglottos", ""),
    92: ("Nighthawk", "Chordeiles minor", "genus=定种为普通夜鹰"),
    93: ("Clark_Nutcracker", "Nucifraga columbiana", ""),
    94: ("White_breasted_Nuthatch", "Sitta carolinensis", ""),
    95: ("Baltimore_Oriole", "Icterus galbula", ""),
    96: ("Hooded_Oriole", "Icterus cucullatus", ""),
    97: ("Orchard_Oriole", "Icterus spurius", ""),
    98: ("Scott_Oriole", "Icterus parisorum", ""),
    99: ("Ovenbird", "Seiurus aurocapilla", ""),
    100: ("Brown_Pelican", "Pelecanus occidentalis", ""),
    101: ("White_Pelican", "Pelecanus onocrotalus", ""),
    102: ("Western_Wood_Pewee", "Contopus sordidulus", ""),
    103: ("Sayornis", "Sayornis saya", "genus=定种为 Say's Phoebe，建议复核"),
    104: ("American_Pipit", "Anthus rubescens", ""),
    105: ("Whip_poor_Will", "Caprimulgus vociferus", ""),
    106: ("Horned_Puffin", "Fratercula corniculata", ""),
    107: ("Common_Raven", "Corvus corax", ""),
    108: ("White_necked_Raven", "Corvus albicollis", ""),
    109: ("American_Redstart", "Setophaga ruticilla", ""),
    110: ("Geococcyx", "Geococcyx californianus", "genus=定种为走鹃"),
    111: ("Loggerhead_Shrike", "Lanius ludovicianus", ""),
    112: ("Great_Grey_Shrike", "Lanius excubitor", ""),
    113: ("Baird_Sparrow", "Ammodramus bairdii", ""),
    114: ("Black_throated_Sparrow", "Amphispiza bilineata", ""),
    115: ("Brewer_Sparrow", "Spizella breweri", ""),
    116: ("Chipping_Sparrow", "Spizella passerina", ""),
    117: ("Clay_colored_Sparrow", "Spizella pallida", ""),
    118: ("House_Sparrow", "Passer domesticus", ""),
    119: ("Field_Sparrow", "Spizella pusilla", ""),
    120: ("Fox_Sparrow", "Passerella iliaca", ""),
    121: ("Grasshopper_Sparrow", "Ammodramus savannarum", ""),
    122: ("Harris_Sparrow", "Zonotrichia querula", ""),
    123: ("Henslow_Sparrow", "Ammodramus henslowii", ""),
    124: ("Le_Conte_Sparrow", "Ammodramus leconteii", ""),
    125: ("Lincoln_Sparrow", "Melospiza lincolnii", ""),
    126: ("Nelson_Sharp_tailed_Sparrow", "Ammodramus nelsoni", ""),
    127: ("Savannah_Sparrow", "Passerculus sandwichensis", ""),
    128: ("Seaside_Sparrow", "Ammodramus maritimus", ""),
    129: ("Song_Sparrow", "Melospiza melodia", ""),
    130: ("Tree_Sparrow", "Spizelloides arborea", ""),
    131: ("Vesper_Sparrow", "Pooecetes gramineus", ""),
    132: ("White_crowned_Sparrow", "Zonotrichia leucophrys", ""),
    133: ("White_throated_Sparrow", "Zonotrichia albicollis", ""),
    134: ("Cape_Glossy_Starling", "Lamprotornis nitens", ""),
    135: ("Bank_Swallow", "Riparia riparia", ""),
    136: ("Barn_Swallow", "Hirundo rustica", ""),
    137: ("Cliff_Swallow", "Petrochelidon pyrrhonota", ""),
    138: ("Tree_Swallow", "Tachycineta bicolor", ""),
    139: ("Scarlet_Tanager", "Piranga olivacea", ""),
    140: ("Summer_Tanager", "Piranga rubra", ""),
    141: ("Artic_Tern", "Sterna paradisaea", ""),
    142: ("Black_Tern", "Chlidonias niger", ""),
    143: ("Caspian_Tern", "Hydroprogne caspia", ""),
    144: ("Common_Tern", "Sterna hirundo", ""),
    145: ("Elegant_Tern", "Thalasseus elegans", ""),
    146: ("Forsters_Tern", "Sterna forsteri", ""),
    147: ("Least_Tern", "Sternula antillarum", ""),
    148: ("Green_tailed_Towhee", "Pipilo chlorurus", ""),
    149: ("Brown_Thrasher", "Toxostoma rufum", ""),
    150: ("Sage_Thrasher", "Oreoscoptes montanus", ""),
    151: ("Black_capped_Vireo", "Vireo atricapilla", ""),
    152: ("Blue_headed_Vireo", "Vireo solitarius", ""),
    153: ("Philadelphia_Vireo", "Vireo philadelphicus", ""),
    154: ("Red_eyed_Vireo", "Vireo olivaceus", ""),
    155: ("Warbling_Vireo", "Vireo gilvus", ""),
    156: ("White_eyed_Vireo", "Vireo griseus", ""),
    157: ("Yellow_throated_Vireo", "Vireo flavifrons", ""),
    158: ("Bay_breasted_Warbler", "Setophaga castanea", ""),
    159: ("Black_and_white_Warbler", "Mniotilta varia", ""),
    160: ("Black_throated_Blue_Warbler", "Setophaga caerulescens", ""),
    161: ("Blue_winged_Warbler", "Vermivora cyanoptera", ""),
    162: ("Canada_Warbler", "Cardellina canadensis", ""),
    163: ("Cape_May_Warbler", "Setophaga tigrina", ""),
    164: ("Cerulean_Warbler", "Setophaga cerulea", ""),
    165: ("Chestnut_sided_Warbler", "Setophaga pensylvanica", ""),
    166: ("Golden_winged_Warbler", "Vermivora chrysoptera", ""),
    167: ("Hooded_Warbler", "Setophaga citrina", ""),
    168: ("Kentucky_Warbler", "Geothlypis formosa", ""),
    169: ("Magnolia_Warbler", "Setophaga magnolia", ""),
    170: ("Mourning_Warbler", "Geothlypis philadelphia", ""),
    171: ("Myrtle_Warbler", "Setophaga coronata", ""),
    172: ("Nashville_Warbler", "Leiothlypis ruficapilla", ""),
    173: ("Orange_crowned_Warbler", "Leiothlypis celata", ""),
    174: ("Palm_Warbler", "Setophaga palmarum", ""),
    175: ("Pine_Warbler", "Setophaga pinus", ""),
    176: ("Prairie_Warbler", "Setophaga discolor", ""),
    177: ("Prothonotary_Warbler", "Protonotaria citrea", ""),
    178: ("Swainson_Warbler", "Limnothlypis swainsonii", ""),
    179: ("Tennessee_Warbler", "Leiothlypis peregrina", ""),
    180: ("Wilson_Warbler", "Cardellina pusilla", ""),
    181: ("Worm_eating_Warbler", "Helmitheros vermivorum", ""),
    182: ("Yellow_Warbler", "Setophaga petechia", ""),
    183: ("Northern_Waterthrush", "Parkesia noveboracensis", ""),
    184: ("Louisiana_Waterthrush", "Parkesia motacilla", ""),
    185: ("Bohemian_Waxwing", "Bombycilla garrulus", ""),
    186: ("Cedar_Waxwing", "Bombycilla cedrorum", ""),
    187: ("American_Three_toed_Woodpecker", "Picoides dorsalis", ""),
    188: ("Pileated_Woodpecker", "Dryocopus pileatus", ""),
    189: ("Red_bellied_Woodpecker", "Melanerpes carolinus", ""),
    190: ("Red_cockaded_Woodpecker", "Leuconotopicus borealis", ""),
    191: ("Red_headed_Woodpecker", "Melanerpes erythrocephalus", ""),
    192: ("Downy_Woodpecker", "Dryobates pubescens", ""),
    193: ("Bewick_Wren", "Thryomanes bewickii", ""),
    194: ("Cactus_Wren", "Campylorhynchus brunneicapillus", ""),
    195: ("Carolina_Wren", "Thryothorus ludovicianus", ""),
    196: ("House_Wren", "Troglodytes aedon", ""),
    197: ("Marsh_Wren", "Cistothorus palustris", ""),
    198: ("Rock_Wren", "Salpinctes obsoletus", ""),
    199: ("Winter_Wren", "Troglodytes hiemalis", ""),
    200: ("Common_Yellowthroat", "Geothlypis trichas", ""),
}


# CUB 俗名 -> 中文名（参考公开名录整理，个别为机翻，可按需校正）
CUB_COMMON_CN = {
    "Black_footed_Albatross": "黑脚信天翁",
    "Laysan_Albatross": "莱岛信天翁",
    "Sooty_Albatross": "乌信天翁",
    "Groove_billed_Ani": "沟嘴犀鹃",
    "Crested_Auklet": "凤头海雀",
    "Least_Auklet": "小海雀",
    "Parakeet_Auklet": "长嘴海雀",
    "Rhinoceros_Auklet": "角嘴海雀",
    "Brewer_Blackbird": "布氏拟八哥",
    "Red_winged_Blackbird": "红翅黑鸟",
    "Rusty_Blackbird": "锈色拟八哥",
    "Yellow_headed_Blackbird": "黄头黑鸟",
    "Bobolink": "刺歌雀",
    "Indigo_Bunting": "靛蓝彩鹀",
    "Lazuli_Bunting": "天青石彩鹀",
    "Painted_Bunting": "彩色彩鹀",
    "Cardinal": "主红雀",
    "Spotted_Catbird": "斑猫鸟",
    "Gray_Catbird": "灰猫鸟",
    "Yellow_breasted_Chat": "黄胸巨莺",
    "Eastern_Towhee": "东方唧鹀",
    "Chuck_will_Widow": "查克氏夜鹰",
    "Brandt_Cormorant": "布氏鸬鹚",
    "Red_faced_Cormorant": "红脸鸬鹚",
    "Pelagic_Cormorant": "远洋鸬鹚",
    "Bronzed_Cowbird": "铜色牛鹂",
    "Shiny_Cowbird": "光泽牛鹂",
    "Brown_Creeper": "褐旋木雀",
    "American_Crow": "美洲乌鸦",
    "Fish_Crow": "鱼鸦",
    "Black_billed_Cuckoo": "黑嘴杜鹃",
    "Mangrove_Cuckoo": "红树林杜鹃",
    "Yellow_billed_Cuckoo": "黄嘴杜鹃",
    "Gray_crowned_Rosy_Finch": "灰顶玫红雀",
    "Purple_Finch": "紫朱雀",
    "Northern_Flicker": "北扑翅䴕",
    "Acadian_Flycatcher": "阿卡迪亚霸鹟",
    "Great_Crested_Flycatcher": "大冠霸鹟",
    "Least_Flycatcher": "小霸鹟",
    "Olive_sided_Flycatcher": "橄榄侧霸鹟",
    "Scissor_tailed_Flycatcher": "剪尾霸鹟",
    "Vermilion_Flycatcher": "朱红霸鹟",
    "Yellow_bellied_Flycatcher": "黄腹霸鹟",
    "Frigatebird": "军舰鸟",
    "Northern_Fulmar": "北方管鼻鹱",
    "Gadwall": "赤膀鸭",
    "American_Goldfinch": "美洲金翅雀",
    "European_Goldfinch": "欧洲金翅雀",
    "Boat_tailed_Grackle": "船尾拟八哥",
    "Eared_Grebe": "黑颈䴙䴘",
    "Horned_Grebe": "角䴙䴘",
    "Pied_billed_Grebe": "斑嘴䴙䴘",
    "Western_Grebe": "西方䴙䴘",
    "Blue_Grosbeak": "蓝色大嘴雀",
    "Evening_Grosbeak": "暮色大嘴雀",
    "Pine_Grosbeak": "松雀",
    "Rose_breasted_Grosbeak": "玫胸大嘴雀",
    "Pigeon_Guillemot": "鸽崖海鸦",
    "California_Gull": "加州鸥",
    "Glaucous_winged_Gull": "灰翅鸥",
    "Heermann_Gull": "赫氏鸥",
    "Herring_Gull": "银鸥",
    "Ivory_Gull": "象牙鸥",
    "Ring_billed_Gull": "环嘴鸥",
    "Slaty_backed_Gull": "灰背鸥",
    "Western_Gull": "西方鸥",
    "Anna_Hummingbird": "安娜蜂鸟",
    "Ruby_throated_Hummingbird": "红喉蜂鸟",
    "Rufous_Hummingbird": "棕煌蜂鸟",
    "Green_Violetear": "绿紫耳蜂鸟",
    "Long_tailed_Jaeger": "长尾贼鸥",
    "Pomarine_Jaeger": "中贼鸥",
    "Blue_Jay": "蓝松鸦",
    "Florida_Jay": "佛罗里达灌丛鸦",
    "Green_Jay": "绿松鸦",
    "Dark_eyed_Junco": "暗眼灯草鹀",
    "Tropical_Kingbird": "热带王霸鹟",
    "Gray_Kingbird": "灰王霸鹟",
    "Belted_Kingfisher": "带鱼狗",
    "Green_Kingfisher": "绿鱼狗",
    "Pied_Kingfisher": "斑翡翠",
    "Ringed_Kingfisher": "环鱼狗",
    "White_breasted_Kingfisher": "白胸翡翠",
    "Red_legged_Kittiwake": "红腿三趾鸥",
    "Horned_Lark": "角百灵",
    "Pacific_Loon": "太平洋潜鸟",
    "Mallard": "绿头鸭",
    "Western_Meadowlark": "西草地鹨",
    "Hooded_Merganser": "头巾秋沙鸭",
    "Red_breasted_Merganser": "红胸秋沙鸭",
    "Mockingbird": "北方嘲鸫",
    "Nighthawk": "美洲夜鹰",
    "Clark_Nutcracker": "克拉克星鸦",
    "White_breasted_Nuthatch": "白胸䴓",
    "Baltimore_Oriole": "巴尔的摩拟黄鹂",
    "Hooded_Oriole": "头巾拟黄鹂",
    "Orchard_Oriole": "果园拟黄鹂",
    "Scott_Oriole": "斯科特拟黄鹂",
    "Ovenbird": "橙顶灶莺",
    "Brown_Pelican": "褐鹈鹕",
    "White_Pelican": "白鹈鹕",
    "Western_Wood_Pewee": "西方林霸鹟",
    "Sayornis": "北美鹟",
    "American_Pipit": "美洲鹨",
    "Whip_poor_Will": "三声夜鹰",
    "Horned_Puffin": "角海鹦",
    "Common_Raven": "普通渡鸦",
    "White_necked_Raven": "白颈渡鸦",
    "American_Redstart": "美洲红尾鸲",
    "Geococcyx": "走鹃",
    "Loggerhead_Shrike": "大头伯劳",
    "Great_Grey_Shrike": "大灰伯劳",
    "Baird_Sparrow": "贝氏麻雀",
    "Black_throated_Sparrow": "黑喉麻雀",
    "Brewer_Sparrow": "布氏麻雀",
    "Chipping_Sparrow": "棕顶麻雀",
    "Clay_colored_Sparrow": "土色麻雀",
    "House_Sparrow": "家麻雀",
    "Field_Sparrow": "田野麻雀",
    "Fox_Sparrow": "狐色麻雀",
    "Grasshopper_Sparrow": "蝗虫麻雀",
    "Harris_Sparrow": "哈里斯麻雀",
    "Henslow_Sparrow": "亨斯洛麻雀",
    "Le_Conte_Sparrow": "勒孔特麻雀",
    "Lincoln_Sparrow": "林肯麻雀",
    "Nelson_Sharp_tailed_Sparrow": "纳尔逊尖尾麻雀",
    "Savannah_Sparrow": "萨瓦纳麻雀",
    "Seaside_Sparrow": "海滨麻雀",
    "Song_Sparrow": "歌带鹀",
    "Tree_Sparrow": "美洲树麻雀",
    "Vesper_Sparrow": "晚祷麻雀",
    "White_crowned_Sparrow": "白冠麻雀",
    "White_throated_Sparrow": "白喉麻雀",
    "Cape_Glossy_Starling": "好望角辉椋鸟",
    "Bank_Swallow": "崖沙燕",
    "Barn_Swallow": "家燕",
    "Cliff_Swallow": "崖燕",
    "Tree_Swallow": "树燕",
    "Scarlet_Tanager": "猩红比蓝雀",
    "Summer_Tanager": "夏比蓝雀",
    "Artic_Tern": "北极燕鸥",
    "Black_Tern": "黑燕鸥",
    "Caspian_Tern": "里海燕鸥",
    "Common_Tern": "普通燕鸥",
    "Elegant_Tern": "丽色燕鸥",
    "Forsters_Tern": "福氏燕鸥",
    "Least_Tern": "小燕鸥",
    "Green_tailed_Towhee": "绿尾唧鹀",
    "Brown_Thrasher": "褐嘲鸫",
    "Sage_Thrasher": "鼠尾草嘲鸫",
    "Black_capped_Vireo": "黑冠绿鹃",
    "Blue_headed_Vireo": "蓝头绿鹃",
    "Philadelphia_Vireo": "费城绿鹃",
    "Red_eyed_Vireo": "红眼绿鹃",
    "Warbling_Vireo": "鸣唱绿鹃",
    "White_eyed_Vireo": "白眼绿鹃",
    "Yellow_throated_Vireo": "黄喉绿鹃",
    "Bay_breasted_Warbler": "栗胸林莺",
    "Black_and_white_Warbler": "黑白林莺",
    "Black_throated_Blue_Warbler": "黑喉蓝林莺",
    "Blue_winged_Warbler": "蓝翅林莺",
    "Canada_Warbler": "加拿大林莺",
    "Cape_May_Warbler": "海角林莺",
    "Cerulean_Warbler": "天蓝林莺",
    "Chestnut_sided_Warbler": "栗侧林莺",
    "Golden_winged_Warbler": "金翅林莺",
    "Hooded_Warbler": "兜帽林莺",
    "Kentucky_Warbler": "肯塔基林莺",
    "Magnolia_Warbler": "木兰林莺",
    "Mourning_Warbler": "悼念林莺",
    "Myrtle_Warbler": "桃金娘林莺",
    "Nashville_Warbler": "纳什维尔林莺",
    "Orange_crowned_Warbler": "橙冠林莺",
    "Palm_Warbler": "棕榈林莺",
    "Pine_Warbler": "松林莺",
    "Prairie_Warbler": "草原林莺",
    "Prothonotary_Warbler": "黄头林莺",
    "Swainson_Warbler": "斯温森林莺",
    "Tennessee_Warbler": "田纳西林莺",
    "Wilson_Warbler": "威尔逊林莺",
    "Worm_eating_Warbler": "食虫林莺",
    "Yellow_Warbler": "黄林莺",
    "Northern_Waterthrush": "北方水鸫莺",
    "Louisiana_Waterthrush": "路易斯安那水鸫莺",
    "Bohemian_Waxwing": "波西米亚太平鸟",
    "Cedar_Waxwing": "雪松太平鸟",
    "American_Three_toed_Woodpecker": "美洲三趾啄木鸟",
    "Pileated_Woodpecker": "北美黑啄木鸟",
    "Red_bellied_Woodpecker": "红腹啄木鸟",
    "Red_cockaded_Woodpecker": "红顶啄木鸟",
    "Red_headed_Woodpecker": "红头啄木鸟",
    "Downy_Woodpecker": "绒啄木鸟",
    "Bewick_Wren": "贝氏鹪鹩",
    "Cactus_Wren": "仙人掌鹪鹩",
    "Carolina_Wren": "卡罗来纳鹪鹩",
    "House_Wren": "家鹪鹩",
    "Marsh_Wren": "沼泽鹪鹩",
    "Rock_Wren": "岩鹪鹩",
    "Winter_Wren": "冬鹪鹩",
    "Common_Yellowthroat": "普通黄喉林莺",
}


def cn_name(common):
    """返回俗名对应的中文名；未知时原样返回。"""
    return CUB_COMMON_CN.get(common, common)


def load_avonet(path=None):
    """加载 AVONET 主性状表（AVONET1_BirdLife），返回 DataFrame。"""
    path = path or AVONET_PATH
    df = pd.read_excel(str(path), sheet_name="AVONET1_BirdLife")
    df["Species1"] = df["Species1"].astype(str).str.strip()
    return df


def build_mapping_frame():
    """把 CUB_TO_SCIENTIFIC 转成 DataFrame。"""
    rows = []
    for cid, (common, sci, note) in CUB_TO_SCIENTIFIC.items():
        rows.append({"class_id": cid, "cub_name": common, "scientific_name": sci, "note": note})
    return pd.DataFrame(rows)


def match_to_avonet(avonet_df=None):
    """把 CUB 200 类对到 AVONET 物种，返回带匹配信息的 DataFrame。

    匹配策略：先精确匹配 BirdLife 学名(Species1)，失败再依次尝试 eBird(Species2)、
    BirdTree(Species3)，同时处理少数已知分类异名。
    """
    if avonet_df is None:
        avonet_df = load_avonet()

    names1 = set(avonet_df["Species1"])
    name2id = dict(zip(avonet_df["Species1"], avonet_df["Species1"].index))

    # 兼容另外两套分类体系（异名处理）
    for sheet, col in [("AVONET2_eBird", "Species2"), ("AVONET3_BirdTree", "Species3")]:
        try:
            sub = pd.read_excel(str(AVONET_PATH), sheet_name=sheet)[col].astype(str).str.strip()
            name2id.update(dict.fromkeys(sub, name2id.get(sub.iloc[0], None)))
            names1 |= set(sub)
        except Exception:
            pass

    rows = []
    unmatched = []
    for cid, (common, sci, note) in CUB_TO_SCIENTIFIC.items():
        hit = sci if sci in names1 else None
        if hit is None:
            unmatched.append((cid, common, sci))
        rows.append({
            "class_id": cid, "cub_name": common, "scientific_name": sci,
            "matched": hit is not None, "note": note,
        })
    return pd.DataFrame(rows), unmatched


def map_to_traits(avonet_df=None):
    """把 CUB 类别映射到 AVONET 性状，返回合并后的 DataFrame。

    返回列包含：class_id, cub_name, scientific_name, 以及 AVONET 的形态/生态性状列。
    """
    if avonet_df is None:
        avonet_df = load_avonet()

    mapping, _ = match_to_avonet(avonet_df)
    joined = mapping.merge(
        avonet_df, left_on="scientific_name", right_on="Species1", how="left"
    )
    return joined
